#!/bin/bash

# create a simple spreadsheet
# mkdir -p sv_test
# echo > sv_test/user-scenarios.csv
# sv_file=sv_test/user-scenarios.csv
sv_file="virtual://"
sv_letter=a
sv_upper=A
. ns run add

sv_letter=a
sv_upper=A
. ns run load
sv_letter=c
sv_upper=C
. ns run add
sv_letter=b # fix the skipped letter
sv_upper=B # fix the skipped letter
. ns run save # bug used to wrongly replace A->B instead of C->B
last=$(tail -1 sv_test/user-scenarios.csv)
test="US1 - Load Then Add Updates Row Number Test"
# . ns run print
if [[ "$last" != "b,B" && "$last" != "B,b" ]]; then
    echo "${test}...FAIL"
else
    echo "${test}...PASS"
fi

. ns delete last sv_letter sv_upper test
. ns delete sv_row sv_sep sv_file

. ns run test-user-scenarios-saves-new-column

. ns run test-user-scenarios-adds-new-column

sv_file=$(cat << EOF
virtual://flag,lower,letter,upper
,a,a,A
,,b,B
Y,c,c,C
EOF
)

test="US4 - Add Or Save 2+ New Vars Does Not Add Column Test" # protects against adding extra columns that were previously loaded from another file and never unset

sv_letter=d
sv_lower=d
sv_upper=D
sv_flag=Y
sv_new_column=d # new column
sv_new_columnd=d # new column
. ns run add 2>/dev/null 1>/dev/null || true
. ns run save 2>/dev/null 1>/dev/null || true
. ns run sv-cat
d_col_cnt=$(echo "$sv_cat" | grep "d" | wc -l)
. ns delete sv_cat
if [[ $d_col_cnt -gt 0 ]]; then
    echo "${test}...FAIL"
else
    echo "${test}...PASS"
fi

. ns delete "sv_*"
. ns delete d_col_cnt

test="US5 - Adding empty var in row, then load it and re-save it"
# sv_file=sv_test/user-scenarios-empty-var-test.csv
# if [[ -f "$sv_file" ]]; then
#     rm "$sv_file"
# fi
sv_file="virtual://"
sv_empty=
sv_other=1
. ns run add
. ns run sv-cat
empty_var_line=$(echo "$sv_cat" | tail -1)
. ns delete sv_cat
capture_row_no="$sv_row"
. ns run load
. ns run save # 2>&1 1>>/dev/null
. ns run sv-cat
wcl=$(echo "$sv_cat" | wc -l)
. ns delete sv_cat
if [[ $wcl -ne 3 && "$sv_row" != 2 && "$capture_row_no" != "1" && "$empty_var_line" != "1," && "$empty_var_line" != ",1" ]]; then
    echo "${test}...FAIL"
else
    echo "${test}...PASS"
fi

. ns delete "sv_*"
. ns delete wcl empty_var_line capture_row_no

test="US6 - Omitted column fails to add row"
# sv_file="sv_test/user-scenarios-omitted.csv"
# if [[ -f "$sv_file" ]]; then
#     rm "$sv_file"
# fi
# echo "title,other,stuff" >> "$sv_file"
sv_file="virtual://title,other,stuff"
sv_title="My Title: My subtitle, and stuff"
sv_other="my data"
# sv_stuff gets omitted
. ns run add 2>/dev/null
ec=$?
. ns run sv-cat
wcl=$(echo "$sv_cat" | wc -l)
. ns delete sv_cat

if [[ $wcl -eq 1 && $ec -eq 0 ]]; then
    echo "${test}...PASS"
else
    echo "${test}...FAIL"
fi

. ns run test-user-scenarios-print-mult-line-comma

. ns run test-user-scenarios-print-header-only-csv

. ns run test-user-scenarios-print-filter-xor

. ns run test-user-scenarios-print-filter-or

. ns run test-user-scenarios-print-filter-and

. ns delete "sv_*"
. ns delete ec
