#!/bin/bash

. ns import svns_rc sv_sep svns_nl_repl

if [[ -z "$sv_sep" ]]; then
    sv_sep=,
fi

if [[ -z svns_nl_repl ]]; then
    svns_nl_repl=0
fi

svns_rc_subst=
# "$svns_rc"

# substitute for a specific row.column

has_sep=$(echo "$svns_rc" | grep "{sv_sep}" | wc -l)
has_qt=$(echo "$svns_rc" | grep '{sv_qt}' | wc -l)
has_nl=$(echo "$svns_rc" | grep '{sv_nl}' |wc -l)

last_index=${#svns_rc}; ((last_index--))
str=
i=0
while [[ $i -lt ${#svns_rc} ]]
do
    c="${svns_rc:$i:1}"
    if [[ $i -eq 0 && "$c" == '"' || $i -eq ${last_index} && "$c" == '"' ]]; then
        if [[ "${has_sep}${has_qt}${has_nl}" != "000" ]]; then
            ((i++))
            continue
        fi
    fi
    if [[ $svns_nl_repl -eq 1 && "${svns_rc:$i:7}" == "{sv_nl}" ]]; then
        str="${str}\n"
        ((i+=7))
        continue
    elif [[ "${svns_rc:$i:8}" == "{sv_sep}" ]]; then
        str="${str}${sv_sep}"
        ((i+=8))
        continue
    elif [[ "${svns_rc:$i:7}" == "{sv_qt}" ]]; then
        str="${str}"$'"'
        ((i+=7))
        continue
    elif [[ "${svns_rc:$i:7}" == "{sv_nl}" ]]; then
        str="${str}"$'\n'
        ((i+=7))
        continue
    fi
    str="${str}${c}"
    ((i++))
done


svns_rc_subst="$str"

. ns export svns_rc_subst sv_sep
