#!/bin/bash

. ns import sv_match_name sv_match_value sv_match_header sv_match_content sv_sep

i=0
idx=-1
saveIFS="$IFS"
IFS="$sv_sep"
for col_name in $sv_match_header
do
    if [[ "$col_name" == "$sv_match_name" ]]; then
        idx=$i
        break
    fi
    ((i++))
done

sv_matches=0
for col_value in $sv_match_content
do
    if [[ "$col_value" == "$sv_match_value" ]]; then
        sv_matches=1
        break
    fi
done
IFS="$saveIFS"



. ns export sv_matches sv_sep


