#!/bin/bash

. ns import sv_match_name sv_match_value sv_match_header sv_match_content sv_sep

# echo "$sv_match_header"
# echo "$sv_match_content"

i=0
idx=-1
saveIFS="$IFS"
IFS="$sv_sep"
for col_name in $sv_match_header
do
    # echo "${col_name} == ${sv_match_name:3}"
    # substring at 3rd char to ignore the leading 'sv_' in the name
    if [[ "$col_name" == "${sv_match_name:3}" ]]; then
        idx=$i
        break
    fi
    ((i++))
done

i=0
sv_matches=0
for col_value in $sv_match_content
do
    # echo "${i} -eq ${idx}. ${col_value} == ${sv_match_value}"
    if [[ $i -eq $idx && "$col_value" == "$sv_match_value" ]]; then
        sv_matches=1
        break
    fi
    ((i++))
done
IFS="$saveIFS"



. ns export sv_matches sv_sep


