#!/bin/bash

. ns import "sv_*"

if [[ -z "$sv_sep" ]]; then
    sv_sep=,
fi

sep="$sv_sep"
file="$sv_file"

dir="${file%/*}"

if [[ ! -f "$file" ]]; then
    echo "sv print failed. '${file}' is not a regular file" >&2
    exit 1
fi

header=
wcl=$(cat "$file" | wc -l)
exists=0
if [[ $wcl -gt 1 ]]; then
    header=$(cat "$file" | head -1)
    exists=1
fi

sizes_csv=
csv=$(tail -n +2 "$sv_file") # everything except 1st line

# DETERMINE COLSIZE VALUES LOOP BLOCK
# STORED AS A SINGLE CSV LINE
# example:
#     a,b,c
#     100,10,1
#     10,1,1
#
#     -> 3,2,1
#
# foreach column
#    foreach line in file
#        TODO: ^USE SYMBOLIC REPRESENTATION TO SUPPORT MULTILINE COLUMNS
#        get column of that line and update the max in the single csv line
#            TODO: ^FOREACH LINE IN COLUMN TO FIND MAX OF MULT. LINES
fieldno=1
row=
saveIFS="$IFS"
IFS="$sep"
for col in $header
do
    max=${#col}
    ((max+=2))
    IFS=$'\n'
    for line in $csv
    do
        test=$(echo "$line" | cut -d "$sep" -f "$fieldno")
        test_len=${#test}
        ((test_len+=2))
        if [[ $test_len -gt $max ]]; then
            max=$test_len
        fi
    done
    if [[ $fieldno -eq 1 ]]; then
        sizes_csv="$max"
    else
        sizes_csv="${sizes_csv},${max}"
    fi
    IFS="$sep"

    ((fieldno++))
done

sp="                                                                                              "
hp="----------------------------------------------------------------------------------------------"
# echo "$sizes_csv" # 77,25,20
border1=" "
for colsz in $sizes_csv
do
    sz=$((colsz+1))
    border1="${border1}+${hp:0:$sz}"
done
border1="${border1}+"
echo
echo "$border1"

fieldno=1
h=" |"
for col in $header
do
    sz=$(echo "$sizes_csv" | cut -d "$sep" -f "$fieldno")
    colsz=${#col}
    sz=$((sz-colsz))
    ((sz-=1))
    h="${h} ${col}${sp:0:$sz} |"
    ((fieldno++))
done
echo "$h"
echo "$border1"
echo
echo "$border1"

# PRINT DATA ROW LOOP BLOCK
# foreach line
#    foreach column in line
#        format column as a part of r (row) print
#            TODO: ^ITERATE LINES IN COLUMN
#            TODO:  & USE A DICTIONARY TO PRINT PREVIOUS COLUMN LINE EXTENSIONS
#    print r (row)
IFS=$'\n'
for line in $csv
do
    r=" |"
    fieldno=1
    IFS="$sep"
    for col in $line
    do
        sz=$(echo "$sizes_csv" | cut -d "$sep" -f "$fieldno")
        colsz=${#col}
        sz=$((sz-colsz))
        ((sz-=1))
        r="${r} ${col}${sp:0:$sz} |"
        ((fieldno++))
    done
    IFS=$'\n'
    echo "$r"
    echo "$border1"
done

echo
IFS="$saveIFS"


. ns run values

. ns export "sv_*"
