#!/bin/bash

. ns import "sv_*"

if [[ -z "$sv_sep" ]]; then
    sv_sep=,
fi

sep="$sv_sep"
file="$sv_file"
rowno="$sv_row"

if [[ -z "$rowno" ]]; then
    echo "sv save row failed due to no previously loaded row found, run the load command first"
    exit 1
fi

virtual_scheme="virtual://"
if [[ "${virtual_scheme}" != "${sv_file:0:${#virtual_scheme}}" && ! -f "$file" ]]; then
    echo "sv save failed. '${file}' is not a regular file" >&2
    exit 1
fi
is_virtual_file=0
if [[ "${virtual_scheme}" == "${sv_file:0:${#virtual_scheme}}" ]]; then
    is_virtual_file=1
fi

newcol=

header=
. ns run sv-cat
wcl=$(echo "$sv_cat" | wc -l)
if [[ $wcl -gt 1 ]]; then
    header=$(echo "$sv_cat" | head -1)

    # save guard
    svfn_sep="$sv_sep"
    svfn_minuend=$(set | grep "^sv_" | cut -d "=" -f1 | tr '\n' "$sv_sep")
    svfn_subtrahend="$header"
    . ns run sv-diff-count
    if [[ $svfn_diff_count -gt 1 ]]; then
        echo "Unable to save 2+ new columns to existing file" >&2
        exit 1
    elif [[ $svfn_diff_count -eq 1 ]]; then
        newcol="$svfn_diff"
    fi
fi


# echo "$header"
row_csv=
saveIFS="$IFS"
IFS="$sep"
for col in $header
do
    name=$(set | grep "^sv_${col}=" | cut -d '=' -f1 | head -1)
    val="${!name}"

    svns_rc="$val"
    svns_nl_repl=1
    . ns run sv-sep-sub-rc-escape  # a{sv_sep}b -> "a,b"
    # echo "$val" "Vs" "$svns_rc_subst"
    val="$svns_rc_subst"

    if [[ -z "$row_csv" ]]; then
        row_csv="$val"
    else
        row_csv="${row_csv}${sep}${val}"
    fi
done
IFS="$saveIFS"

. ns run linespan
lineno=$svfn_lspan_i

# echo "$lineno"
# echo "$row_csv"

if [[ $svfn_lspan_len -gt 1 ]]; then
    start=$((svfn_lspan_i+1))
    end=$((svfn_lspan_i+svfn_lspan_len-1))
    # echo will delete "${start},${end}d" "$sv_file"
    if [[ $is_virtual_file -eq 0 ]]; then
        sed -i -e "${start},${end}d" "$sv_file"
    else
        sv_file=$(echo "$sv_cat" | sed -e "${start},${end}d")
        sv_file="virtual://${sv_file}"
    fi
fi

# echo will replace "${lineno} c${row_csv}" "$sv_file"
if [[ $is_virtual_file -eq 0 ]]; then
    sed -i "${lineno} c${row_csv}" "$sv_file"
else
    sv_file=$(echo "$sv_cat" | sed "${lineno} c${row_csv}")
    sv_file="virtual://${sv_file}"
fi
. ns delete svfn_lspan_i svfn_lspan_len

. ns delete sv_cat


if [[ -n "$newcol" ]]; then
    save_sv_row="$sv_row"
    svfn_newcol="$newcol"
    . ns run add-col
    sv_row="$save_sv_row"
fi


. ns export "sv_*"
