# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: ci
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Repo Checkout
        uses: actions/checkout@v4
        
      - uses: actions/checkout@v4
        with:
          repository: koreyhinton/dot-ns
          path: './dot-ns'

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          repo="${PWD}"
          pwd
          ls -al ./
          echo "${PWD}/dot-ns"
          ls -al "${PWD}/dot-ns"
          echo 1 && export PATH="${PATH}:${PWD}:${PWD}/dot-ns"
          echo 2 && mkdir -p files
          echo 3 && cd files
          echo 4 && . ../sv.profile
          echo 5 && sv
          echo 5.5 && ls -l "${repo}/dot-ns/ns"
          echo 5.51 && which ns
          echo 6 && svskip=y tests=`. ns run test`
          echo 7 && echo "$tests"
          fail_cnt=$(echo "$tests" | grep FAIL | wc -l)
          if [[ $fail_cnt -gt 0 ]]; then false; else true; fi
